import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          DEFAULT: "var(--color-primary-400)",
          dark: "var(--color-primary-600)",
        },
        success: {
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          DEFAULT: "var(--color-success-500)",
        },
        warning: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          DEFAULT: "var(--color-warning-500)",
        },
        danger: {
          50: "var(--color-danger-50)",
          100: "var(--color-danger-100)",
          200: "var(--color-danger-200)",
          300: "var(--color-danger-300)",
          400: "var(--color-danger-400)",
          500: "var(--color-danger-500)",
          600: "var(--color-danger-600)",
          700: "var(--color-danger-700)",
          800: "var(--color-danger-800)",
          900: "var(--color-danger-900)",
          DEFAULT: "var(--color-danger-500)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          "2": "var(--color-surface-2)",
          "3": "var(--color-surface-3)",
        },
        text: {
          "1": "var(--color-text-1)",
          "2": "var(--color-text-2)",
          "3": "var(--color-text-3)",
        },
        border: "var(--color-border)",
        "border-light": "var(--color-border-light)",
      },
      fontSize: {
        xs: ["11px", "1.5"],
        sm: ["13px", "1.6"],
        base: ["15px", "1.7"],
        lg: ["18px", "1.4"],
        xl: ["24px", "1.3"],
        "2xl": ["32px", "1.2"],
        "3xl": ["48px", "1.1"],
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans Arabic", "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "16px",
        xl: "24px",
        btn: "10px",
        card: "16px",
      },
      boxShadow: {
        soft: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "glow-green": "0 0 20px rgba(0, 212, 170, 0.3), 0 0 60px rgba(0, 212, 170, 0.1)",
        "glow-red": "0 0 12px rgba(255, 77, 109, 0.3), 0 0 24px rgba(255, 77, 109, 0.1)",
        neumorphic: "var(--shadow-neumorphic)",
        "neumorphic-inset": "var(--shadow-neumorphic-inset)",
      },
      backdropBlur: {
        glass: "20px",
        "glass-strong": "32px",
      },
    },
  },
  plugins: [],
};
export default config;
